# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-02 16:58
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('pangra', '0003_auto_20180102_2235'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='entry',
            managers=[
                ('entries', django.db.models.manager.Manager()),
            ],
        ),
    ]
