# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-02 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pangra', '0004_auto_20180102_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='headline',
            field=models.CharField(default='hh', max_length=255),
            preserve_default=False,
        ),
    ]
